name: App Runner Secrets Deploy

on:
  push:
    branches:
      - main

env:
  DUPLO_HOST: https://duplo.cloud.myfo.tech
  DUPLO_TOKEN: "AQAAANCMnd8BFdERjHoAwE_Cl-sBAAAAKZ2g7FkUHUOIMI1QmJb1nAAAAAACAAAAAAAQZgAAAAEAACAAAACCQhZ6oX_wHPD2vYsCRpR7EHFMLWKPUoETIWbJdyQ0MQAAAAAOgAAAAAIAACAAAACQLuOqz0d_puqGl9wY0KyWzu5x7oNwtTXWI6X5UULMLsAAAADzGUjQoEdMyk7j2FTgNUKu8s1l0iy3XZfixWeIQDZIvQtzbABlCel4KThrvmGZptVmUg3vu0kG1xpy7c48EVJkxSML1jHu4Az0d9BaeqSTNHWpgOLKZTDnWwLpAfYTK4fdiur70ZFagEtBkAgTU6k5XZEyAzpWH_Z1kcbDBSvMWmtgOqmwPKEOMH6G1CC0EDz_PY1WeC2BN73NucW7sLyT2RAexPy3H8pN2ZJGKpaLBddcw6vIFfm5pvCqxWE8A2BAAAAAz25avof4Eejd04wuuC-30_7v4Rc3h58nkgL3DClerpOl5Q13z2HfLZPOyMasaFeiuD9dZMPU8NroRLEDFrNJBg"
  DUPLO_TENANT: stage
  SECRET_NAME: test-env-secret
  SERVICE_ARN: arn:aws:apprunner:us-east-1:387659052797:service/test-nginx-apprunner/535dc40db71d4411a71e4f0d9488d643
  AWS_REGION: us-east-1

jobs:
  deploy_apprunner_secrets:
    name: Update App Runner with Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup AWS Credentials via Duplo
        uses: duplocloud/actions@main

      - name: Make scripts executable
        run: chmod +x ci/*.sh

      - name: Generate source-config.json
        run: ./ci/generate-source-config.sh

      - name: Update App Runner Service
        run: ./ci/update-app-runner.sh
