name: App Runner Secrets Deploy

on:
  push:
    branches:
      - main

env:
  DUPLO_HOST: https://duplo.cloud.myfo.tech
  DUPLO_TOKEN: "AQAAANCMnd8BFdERjHoAwE_Cl-sBAAAAKZ2g7FkUHUOIMI1QmJb1nAAAAAACAAAAAAAQZgAAAAEAACAAAABZdnQjAnZ7Sf5sNgwEjVHNtACpt1VUyROzdBVwNY9INQAAAAAOgAAAAAIAACAAAAC6T8DO2tWNRMPgvsDAYKdpxVXsErjiFHFTW5u2kilRoMAAAAAatXM0mboL38zYKblZxwsL-3Y6dqi3mQbAUoHdSoVWxAWUBrylvTRYE2vobhVHBa_rp5yE1cWfcp53J37d5NjRtdrVjL0dZkyD-Ywd-R7wr4hbKhGod0DgMbXh8_vTHM3RNUU4fqEwazfpSDYJqMmPJzV4csh93vUGNzBj55dT6MWLtN6HVd8GJsH6nG5Xc6sjd6A7A2bNmxMSMdvValwEJgwIlYU0hwRbz__45cVuddT65uUcjlU7JwndehYbBptAAAAACE1LbruCvp9t1SHSaH6kHDBrF0_X8Rq6RmWgWzf5hk4xoElSajfLrPHeqfMwmd9ZxoJVTtVVwWkMDkvT-CV9ZQ"
  DUPLO_TENANT: stage
  SECRET_NAME: test-env-secret
  SERVICE_ARN: arn:aws:apprunner:us-east-1:387659052797:service/test-nginx-apprunner/535dc40db71d4411a71e4f0d9488d643
  AWS_REGION: us-east-1

jobs:
  deploy_apprunner_secrets:
    name: Update App Runner with Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup AWS Credentials via Duplo
        uses: duplocloud/actions@main

      - name: Make scripts executable
        run: chmod +x ci/*.sh

      - name: Generate source-config.json
        run: ./ci/generate-source-config.sh

      - name: Update App Runner Service
        run: ./ci/update-app-runner.sh
